version: 0.0
os: windows
files:
  - source: \index.html
    destination: C:\inetpub\wwwroot\mkdir "%APPLICATION_NAME%"\App_Data
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
